ln -ris dotfiles/.vim .vim
ln -ris dotfiles/.bashrc .bashrc
ln -ris dotfiles/.bash_aliases .bash_aliases
ln -ris dotfiles/.bash_profile .bash_profile
ln -ris dotfiles/.vimrc .vimrc
ln -ris dotfiles/.viminfo .viminfo
ln -ris dotfiles/.Xmodmap .Xmodmap
ln -ris dotfiles/.i3/config .i3/config
ln -ris dotfiles/i3status.conf /etc/i3status.conf
ln -ris dotfiles/.config/terminator/config .config/terminator/config
